### ISSUE TITLE
Not getting repeat events series using getEvents?

### ISSUE THREAD

**Issue by AP25** [Espesen/public-google-calendar#1]
I have created repeat event in my calendar and made that calender public. 
But using getEvents methods i am getting 1st day repeat event only.I am not getting other event of that series.Or from that 1st day event information its unable to judge that it is repeat event.How to get repeat event series information ?

Thanks in advance

**Comment by Espesen** [comment]
Thanks for your request. I added a dev branch: 8d90afc2cf120b5b1b6abfe09a0814901c415139 where recurring events are expanded. Please let me know if it works in your case!

**Comment by Espesen** [comment]
A bug fix to the preceding: 466dd3cd931ead4682a02e419ae5fd3f6224a738
