### ISSUE TITLE
Doesn't work with infinite recurring events

### ISSUE THREAD

**Issue by RichardLitt** [Espesen/public-google-calendar#2]
Or, I suspect that is the issue. It is currently hanging for me. Trying with: https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com

**Comment by Espesen** [comment]
Thanks for your comment. This should be solved in today's [commit](https://github.com/Espesen/public-google-calendar/commit/1da8b27516854f4ecb7a0567505ec28ce0a8fc0a) (0.2.0), please let me know if it doesn't work for you!

**Comment by RichardLitt** [comment]
@Espesen Thank you so much! That was incredibly useful; it now works.
