### ISSUE TITLE
Confused how to use this with any other code?

### ISSUE THREAD

**Issue by benslv** [Espesen/public-google-calendar#5]
What's the correct way to implement this function?  
Whenever I try and console.log its value outside of the function, it always returns `undefined`. I'm guessing that's because it takes a bit of time to return the value from the calendar?

How can I "extract" the events from the PublicGoogleCalendar instance to use elsewhere?

**Comment by Espesen** [comment]
I added example.js, hope it helps!

I also noticed that some public calendars don't have ical URLs or at least I couldn't find them.

**Comment by benslv** [comment]
Thank you for the help! I'm still having a little trouble working out how to use the data it returns (other than using console.log) since it seems to be acting asynchronously to the rest of the code. If I wanted to, say, save the events to a variable outside of `publicGoogleCalendar.getEvents()` how might I be able to do so?
